apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-bmws-creator-binding
subjects:
  - kind: ServiceAccount
    name: crossplane
    namespace: crossplane-system
roleRef:
  kind: ClusterRole
  name: bmws-crud
  apiGroup: rbac.authorization.k8s.io
